name: Build and publish Zenoh BUS docker image to Docker Hub

on:
  workflow_dispatch:

jobs:
  build_arm:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          image: tonistiigi/binfmt:latest
          platforms: arm64
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: rossonet
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: zenoh_docker
          platforms: linux/arm64
          push: true
          tags: rossonet/zenohd:arm
  build_intel:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          image: tonistiigi/binfmt:latest
          platforms: amd64
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: rossonet
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: zenoh_docker
          platforms: linux/amd64
          push: true
          tags: rossonet/zenohd:intel
  multi_platform_image:
    runs-on: ubuntu-latest
    needs: [build_intel, build_arm]
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: rossonet
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - run: |
          docker pull --platform amd64 rossonet/zenohd:intel
          docker pull --platform arm64 rossonet/zenohd:arm
          d_intel=$(docker manifest inspect rossonet/zenohd:intel |  jq -r '.manifests[] | select(.platform.architecture=="amd64") .digest')
          d_arm=$(docker manifest inspect rossonet/zenohd:arm |  jq -r '.manifests[] | select(.platform.architecture=="arm64") .digest')
          docker manifest create rossonet/zenohd:latest rossonet/zenohd@$d_intel rossonet/zenohd@$d_arm
          docker manifest push rossonet/zenohd:latest
  security-check:
    runs-on: ubuntu-latest
    needs: [build_intel]
    steps:
      - name: Install Trivy
        uses: aquasecurity/setup-trivy@v0.2.2
        with:
          version: v0.59.1
          cache: true
      - run: |
          docker pull --platform amd64 rossonet/zenohd:latest
          docker images
      - name: Avvia container filesystem 
        run: docker run --rm --name test -d rossonet/zenohd:latest
      - name: Export container disk 
        run: docker export test -o trivy.export && mkdir trivy_disk && tar -xvf trivy.export -C trivy_disk
      - name: Stop container 
        run: docker stop test
      - name: Run security check report
        run: trivy rootfs trivy_disk > trivy-report.txt
      - name: Run security check report
        run: trivy rootfs -f cyclonedx --scanners vuln trivy_disk > cyclonedx.json
      - uses: actions/upload-artifact@v4
        with:
          name: trivy_report_zenoh_app
          path: trivy-report.txt
      - uses: actions/upload-artifact@v4
        with:
          name: cyclonedx_zenoh_app
          path: cyclonedx.json

